# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts-jessie-browsers-legacy

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Print Docker image name
          command: echo "$DOCKER_USERNAME/analytics-frontend:$(echo $CIRCLE_BRANCH | tr -dc '[:alnum:]\n\r' | tr '[:upper:]' '[:lower:]')"

      - run:
          name: Build Docker image
          command: docker build -t $DOCKER_USERNAME/analytics-frontend:$(echo $CIRCLE_BRANCH | tr -dc '[:alnum:]\n\r' | tr '[:upper:]' '[:lower:]') .

      - add_ssh_keys:
          fingerprints:
            - "fe:b1:c8:73:4c:fd:f9:6f:b9:84:56:6a:bc:ad:03:c8"
      - run:
          name: Push Docker image
          command: |
            echo $DOCKER_PWD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push $DOCKER_USERNAME/analytics-frontend:$(echo $CIRCLE_BRANCH | tr -dc '[:alnum:]\n\r' | tr '[:upper:]' '[:lower:]')

workflows:
  version: 2
  build-and-deploy-master:
    jobs:
      - build:
          context: Access
